package org.ogema.devicefinder.api;

import org.ogema.core.model.simple.SingleValueResource;
import org.ogema.model.extended.alarming.AlarmConfiguration;

import de.iwes.widgets.api.messaging.MessagePriority;
import de.iwes.widgets.template.LabelledItem;

/** An alarming extension defines an additional alarming evaluation that can be applied
 * to any {@link SingleValueResource}. For implementation information see {@link AlarmingExtensionListener}.
 * 
 * Note that we currently implement to functionalities that are usually separated here: Generation of additional
 * base alarms and generation of AlarmOngoingGroups
 *
 */
public interface AlarmingExtension extends LabelledItem {
	/** The method shall be able to handle a null argument asking whether the extension
	 * shall be offered at all on the general page
	 * @param res
	 * @return
	 */
	boolean offerInGeneralAlarmingConfiguration(AlarmConfiguration ac);
	
	AlarmingExtensionListener getListener(SingleValueResource res, AlarmConfiguration ac);
	
	/** Called when alarming is started. The extension may define an own timer here that
	 * shall be closed on stop. This can be used to perform actions when no alarm occur*/
	default void onStartAlarming() {}

	/** Called when alarming is stopped*/
	default void onStopAlarming() {}
	
	/**Return true if the extension shall receive notifications, which is usually relevant
	 * if alarm groups shall be generated
	 */
	default boolean getAlarmNotifications( ) {return false;}
	
	public static class AlarmNotificationResult {
		//public List<AlarmOngoingGroup> newGroups;
		//public List<AlarmOngoingGroup> changedGroups;
		//public List<AlarmOngoingGroup> finishedGroups;
		/** If true the alarm shall be generated into a message by the framework directly.
		 * Otherwise the {@link AlarmingExtension} will generate one or more messages for
		 * the groups affected
		 */
		public boolean sendAlarmDirectly;
	}
	
	public static abstract class BaseAlarm {
		public AlarmConfiguration ac;
		public String title;
		public String message;
		/** null if generated by framework*/
		public AlarmingExtension source;
		public boolean isNoValueAlarm;
		public boolean isRelease;
		
		public abstract void sendMessage(String title, String message, MessagePriority prio);
	}
	
	/** Notification on a new alarm generated by another extension*/
	default AlarmNotificationResult newAlarmNotification(BaseAlarm baseAlarm) {return null;}
}
